
# odds scrape

In [1]:
# import libraries
import requests  
from datetime import date as dt
from splinter import Browser

from bs4 import BeautifulSoup as soup
import pandas as pd
from datetime import date as dt
from webdriver_manager.chrome import ChromeDriverManager
import time




 # Initiate headless driver for deployment
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\the_f\.wdm\drivers\chromedriver\win32\99.0.4844.51]

In [2]:

url = 'https://www.pinnacle.com/en/baseball/matchups'
browser.visit(url)
browser.execute_script("window.scrollTo(0,document.body.scrollHeight)")
time.sleep(3)



# Convert the browser html to a soup object and then quit the browser
html = browser.html
news_soup = soup(html, 'html.parser')

# Get each live hockey matchup with current live odds

In [3]:
yes = news_soup.find_all("span", {"class":"ellipsis event-row-participant style_participant__32s23"})
i = 0
print("\033[1mCurrent live NHL matches with odds at time of retrieval \033[0m")
print("")
for row in yes:  
    print(yes[i].get_text())
    if i%2 == 0:
        print("vs")
        i = i + 1
    else: 
        print(" ")
        i = i+1
yes

Current live NHL matches with odds at time of retrieval

Tampa Bay Rays
vs
Boston Red Sox

Philadelphia Phillies
vs
Detroit Tigers

Minnesota Twins
vs
Atlanta Braves

Miami Marlins
vs
St. Louis Cardinals

Toronto Blue Jays
vs
New York Yankees

Washington Nationals
vs
New York Mets

Oakland Athletics
vs
Cleveland Guardians

Cincinnati Reds
vs
San Francisco Giants

Los Angeles Angels
vs
Chicago White Sox

Chicago Cubs
vs
San Diego Padres

Texas Rangers
vs
Colorado Rockies

Seattle Mariners
vs
Milwaukee Brewers

Pittsburgh Pirates
vs
Baltimore Orioles

Los Angeles Dodgers
vs
Kansas City Royals

[<span class="ellipsis event-row-participant style_participant__32s23">Tampa Bay Rays</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Boston Red Sox</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Philadelphia Phillies</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Detroit Tigers</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Minnesota Twins</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Atlanta Braves</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Miami Marlins</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">St. Louis Cardinals</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Toronto Blue Jays</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">New York Yankees</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Washington Nationals</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">New York Mets</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Oakland Athletics</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Cleveland Guardians</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Cincinnati Reds</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">San Francisco Giants</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Los Angeles Angels</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Chicago White Sox</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Chicago Cubs</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">San Diego Padres</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Texas Rangers</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Colorado Rockies</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Seattle Mariners</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Milwaukee Brewers</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Pittsburgh Pirates</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Baltimore Orioles</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Los Angeles Dodgers</span>,
 <span class="ellipsis event-row-participant style_participant__32s23">Kansas City Royals</span>]

In [4]:
yess = news_soup.find_all("span", {"class" : "style_price__3LrWW"})
for row in yess:
    lines = row.get_text()
    print(lines)

2.070
1.800
2.140
1.751
2.160
1.735
2.160
1.735
2.100
1.781
2.490
1.568
2.200
1.714
2.290
1.662
2.200
1.709
2.200
1.709
2.110
1.769
2.370
1.621
2.080
1.793
1.740
2.150

In [5]:
# columns = [["one", "two"]]
# NHL_odds = pd.DataFrame(columns = columns)

# team1 = "Tampa Bay"
# Odds1 = "1.38"
# series1 = pd.Series([team1, Odds1], index=["one", "two"])
# NHL_odds.append(series1, ignore_index=True)
MLB_odds = pd.DataFrame({"Matchup": [],
                   "Odds": []})
i = 0
for line, lines in zip(yes, yess):
    teamname = line.get_text()
    odds = lines.get_text()
    MLB_odds.loc[i] = [teamname, odds]
    i = i +1
MLB_odds

                  Matchup   Odds
0          Tampa Bay Rays  2.070
1          Boston Red Sox  1.800
2   Philadelphia Phillies  2.140
3          Detroit Tigers  1.751
4         Minnesota Twins  2.160
5          Atlanta Braves  1.735
6           Miami Marlins  2.160
7     St. Louis Cardinals  1.735
8       Toronto Blue Jays  2.100
9        New York Yankees  1.781
10   Washington Nationals  2.490
11          New York Mets  1.568
12      Oakland Athletics  2.200
13    Cleveland Guardians  1.714
14        Cincinnati Reds  2.290
15   San Francisco Giants  1.662
16     Los Angeles Angels  2.200
17      Chicago White Sox  1.709
18           Chicago Cubs  2.200
19       San Diego Padres  1.709
20          Texas Rangers  2.110
21       Colorado Rockies  1.769
22       Seattle Mariners  2.370
23      Milwaukee Brewers  1.621
24     Pittsburgh Pirates  2.080
25      Baltimore Orioles  1.793
26    Los Angeles Dodgers  1.740
27     Kansas City Royals  2.150

In [6]:

url = 'https://www.pinnacle.com/en/hockey/matchups/'
browser.visit(url)
browser.is_element_present_by_css('div.list_text', wait_time=10)

# Convert the browser html to a soup object and then quit the browser
html = browser.html
news_soup = soup(html, 'html.parser')
yesss = news_soup.find_all("span", {"class":"ellipsis event-row-participant style_participant__32s23"})
yessss = news_soup.find_all("span", {"class" : "style_price__3LrWW"})
NHL_odds = pd.DataFrame({"Matchup": [],
                   "Odds": []})
i = 0
for line, lines in zip(yesss, yessss):
    teamname = line.get_text()
    odds = lines.get_text()
    NHL_odds.loc[i] = [teamname, odds]
    i = i +1
NHL_odds

                Matchup   Odds
0    New York Islanders  2.610
1         Boston Bruins  1.555
2   Tampa Bay Lightning  1.420
3     Detroit Red Wings  3.090
4    Chicago Blackhawks  2.630
5  Vegas Golden Knights  1.549
6     New Jersey Devils  2.500
7   Washington Capitals  1.598

In [7]:
yesss = news_soup.find_all("span", {"class":"ellipsis event-row-participant style_participant__32s23"})
yessss = news_soup.find_all("span", {"class" : "style_price__3LrWW"})
NHL_odds = pd.DataFrame({"Teams": [],
                   "Odds": []})
i = 0
for line, lines in zip(yesss, yessss):
    teamname = line.get_text()
    odds = lines.get_text()
    NHL_odds.loc[i] = [teamname, odds]
    i = i +1
NHL_odds

                  Teams   Odds
0    New York Islanders  2.610
1         Boston Bruins  1.555
2   Tampa Bay Lightning  1.420
3     Detroit Red Wings  3.090
4    Chicago Blackhawks  2.630
5  Vegas Golden Knights  1.549
6     New Jersey Devils  2.500
7   Washington Capitals  1.598

In [8]:
NHL_odds1 = pd.DataFrame({"Home": [],
                   "ML H": [], "Away":[],
                        "ML A":[]})

In [9]:
i = 0
awaylist = []
homelist = []
while (i < (len(NHL_odds)-1)):
    
    awaylist.append(NHL_odds['Teams'][i])
    
    homelist.append(NHL_odds['Teams'][i+1])
    i = i+2

In [10]:
i = 0
awayodds = []
homeodds = []
while (i < (len(NHL_odds)-1)):
    
    awayodds.append(NHL_odds['Odds'][i])
    
    homeodds.append(NHL_odds['Odds'][i+1])
    i = i+2

In [11]:
NHL_odds1["Home"] = homelist
NHL_odds1["Away"] = awaylist
NHL_odds1['ML H'] = homeodds
NHL_odds1['ML A'] = awayodds

In [12]:
NHL_odds1

                   Home   ML H                 Away   ML A
0         Boston Bruins  1.555   New York Islanders  2.610
1     Detroit Red Wings  3.090  Tampa Bay Lightning  1.420
2  Vegas Golden Knights  1.549   Chicago Blackhawks  2.630
3   Washington Capitals  1.598    New Jersey Devils  2.500

In [13]:
MLB_odds1 = pd.DataFrame({"Home": [],
                   "ML H": [], "Away":[],
                        "ML A":[]})
len(MLB_odds)

28

In [14]:
i = 0
awaylist = []
homelist = []
while (i < (len(MLB_odds)-1)):
    
    awaylist.append(MLB_odds['Matchup'][i])
    
    homelist.append(MLB_odds['Matchup'][i+1])
    i = i+2    
homelist
awaylist

['Tampa Bay Rays',
 'Philadelphia Phillies',
 'Minnesota Twins',
 'Miami Marlins',
 'Toronto Blue Jays',
 'Washington Nationals',
 'Oakland Athletics',
 'Cincinnati Reds',
 'Los Angeles Angels',
 'Chicago Cubs',
 'Texas Rangers',
 'Seattle Mariners',
 'Pittsburgh Pirates',
 'Los Angeles Dodgers']

In [15]:
i = 0
awayodds = []
homeodds = []
while (i <= (len(MLB_odds)-1)):
    
    awayodds.append(MLB_odds['Odds'][i])
    homeodds.append(MLB_odds['Odds'][i+1])
    i = i+2    
awayodds

['2.070',
 '2.140',
 '2.160',
 '2.160',
 '2.100',
 '2.490',
 '2.200',
 '2.290',
 '2.200',
 '2.200',
 '2.110',
 '2.370',
 '2.080',
 '1.740']

In [16]:
MLB_odds1["Home"] = homelist
MLB_odds1["Away"] = awaylist
MLB_odds1['ML H'] = homeodds
MLB_odds1['ML A'] = awayodds

In [17]:
MLB_odds1

                    Home   ML H                   Away   ML A
0         Boston Red Sox  1.800         Tampa Bay Rays  2.070
1         Detroit Tigers  1.751  Philadelphia Phillies  2.140
2         Atlanta Braves  1.735        Minnesota Twins  2.160
3    St. Louis Cardinals  1.735          Miami Marlins  2.160
4       New York Yankees  1.781      Toronto Blue Jays  2.100
5          New York Mets  1.568   Washington Nationals  2.490
6    Cleveland Guardians  1.714      Oakland Athletics  2.200
7   San Francisco Giants  1.662        Cincinnati Reds  2.290
8      Chicago White Sox  1.709     Los Angeles Angels  2.200
9       San Diego Padres  1.709           Chicago Cubs  2.200
10      Colorado Rockies  1.769          Texas Rangers  2.110
11     Milwaukee Brewers  1.621       Seattle Mariners  2.370
12     Baltimore Orioles  1.793     Pittsburgh Pirates  2.080
13    Kansas City Royals  2.150    Los Angeles Dodgers  1.740

In [19]:
todaysdate = dt.today()

filename = f'NHL_Odds_{todaysdate}.csv'
NHL_odds1.to_csv(filename, index=False)

todaysdate = dt.today()

filename = f'MLB_Odds_{todaysdate}.csv'
MLB_odds1.to_csv(filename, index=False)